# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4
# This is an example of using VeraDemoDotNet test application with the Veracode Static Pipeline scanner.  A Veracode subscription is required.

##  Main Branch

trigger:
- none

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
# - task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: 'Debug'


# - task: VSTest@2
#   inputs:
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'

- task: DownloadPipelineArtifact@2
  inputs:
    patterns: '**/*.exe,**/*.dll,**/*.pdb' # ensures Veracode gets the PDB files for Static Analysis

# Add a task here to remove additional runtime files that are not needed for the upload such as the roslyn directory if it is present. Reupload the new artifact and use that artifact for scanning

# This task makes the pipeline build artifacts available in a known location for upload to Veracode
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(build.artifactstagingdirectory)\Verademo-dotnet.zip'
    artifactName: Debug

####################################################################################################
## Veracode SCAN
####################################################################################################
####################################################
# Upload and Scan
# ####################################################

- task: Veracode@3
  continueOnError: true
  inputs:
    ConnectionDetailsSelection: 'Service Connection'
    AnalysisService: 'APIServiceAccount'
    veracodeAppProfile: 'Verademo-net'
    version: '$(build.buildNumber)'
    filepath: '$(build.artifactstagingdirectory)'
    sandboxName: 'ADO'
    createSandBox: true
    createProfile: true
    failBuildIfUploadAndScanBuildStepFails: true
    importResults: true
    failBuildOnPolicyFail: false
    maximumWaitTime: '360'

#################################################################
# Pipeline Scanner
#################################################################
## https://docs.veracode.com/r/Pipeline_Scan
- task: CmdLine@2
  displayName: Veracode Static Pipeline Scanner
  continueOnError: true
  inputs:
    script: |
      curl -sSO https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
      unzip -o pipeline-scan-LATEST.zip
      echo "----------------------------------------------------- Pulling down a policy to use in a pipeline scan -----------------------------------------------------"
      java -jar pipeline-scan.jar -vid $(VERACODE_API_ID) -vkey $(VERACODE_API_KEY) -rp "Vulnerable Policy 2"

      echo "----------------------------------------------------- Running a pipeline scan with a policy -----------------------------------------------------"

      java -jar pipeline-scan.jar -vid $(VERACODE_API_ID) -vkey $(VERACODE_API_KEY) -f $(build.artifactstagingdirectory)\Verademo-dotnet.zip -id true -sd true -pf "Vulnerable_Policy_2.json"
########################################################
# Pipeline scan fail on CWE
########################################################
- task: PowerShell@2
  displayName: Veracode Static Pipeline Scanner
  continueOnError: true
  inputs:
    targetType: 'inline'
    script: |
      java -jar pipeline-scan.jar -vid $(VERACODE_API_ID) -vkey $(VERACODE_API_KEY) -f $(build.artifactstagingdirectory)\Verademo-dotnet.zip -id true -sd true -fc "117,81,80"

########################################################
# SCA Agent Based scan
########################################################
# https://docs.veracode.com/r/Veracode_SCA_Agent_Commands
# https://docs.veracode.com/r/c_sc_ci_script
# Note this is using the SCA Agent Based Org Agent
- task: PowerShell@2
  displayName: Veracode SCA Scanner
  continueOnError: true
  inputs:
    targetType: 'inline' #Before it was looking for powershell script to execute, and the target type by default is filepath
    script: |
      Set-ExecutionPolicy AllSigned -Scope Process -Force
      iex ((New-Object System.Net.WebClient).DownloadString('https://download.srcclr.com/ci.ps1')) 
      srcclr scan --update-advisor --allow-dirty --ws $(WORKSPACE_SLUG)
  env:
    SRCCLR_API_TOKEN: $(SRCCLRTOKEN)


####################################################################
# Veracode Flaw Importer
####################################################################


# - task: Veracode Flaw Importer@3
#   inputs:
#     ConnectionDetailsSelection: 'Service Connection'
#     AnalysisService: 'APIServiceAccount'
#     failBuildIfFlawImporterFails: true
#     veracodeAppProfile: '$(system.teamProject)'
#     sandboxName: 'ADO'
#     scanType: 'Dynamic, Static'
#     importType: 'All Flaws Violating Policy'
#     workItemType: 'Bug'
#     area: '$(system.teamProject)'
#     overwriteAreaPathInWorkItemsOnImport: true
#     iterationPath: '$(system.teamProject)'
#     addCweAsATag: true
#     foundInBuild: true
#     addScanNameAsATag: true
#     flawImportLimit: '1000'


#################################################
# Downloading and Running API Wrapper
#################################################
# https://docs.veracode.com/r/c_about_wrappers
# Optionally can trigger DAST Scans as well from here or make API calls

# example using DAST Essentials

# - task: Bash@3
#   env:
#     VERACODE_API_KEY_SECRET: $(VERACODE_API_KEY)
#     VERACODE_API_KEY_ID: $(VERACODE_API_ID)
#   inputs:
#     targetType: 'inline'
#     script: |
#       pip install httpie
#       pip install veracode-api-signing
#       http --auth-type=veracode_hmac --check-status --ignore-stdin -o getguid.json "https://api.veracode.com/appsec/v1/applications?name=$env:APPNAME"
#       http --auth-type=veracode_hmac --check-status --ignore-stdin -o $env:APPNAME-SBOM.json "https://api.veracode.com/srcclr/sbom/v1/targets/$(cat getguid.json | jq -r '._embedded.applications[0].guid')/cyclonedx?type=application"
#       echo "SBOM written to $(APPNAME)-SBOM.json"

# or can trigger it using the DA using the REST API:
## ########################################################################
## # Submitting a DAST scan from the pipeline
## ########################################################################
# #########################################################################
# # Output of configuration json
# #########################################################################
# # The following task writes the input.json from a variable set inline to a file to then be ported to the API call
# # Note: There is a slightly differnt call, and possibly some additonal fields that are needed when updating a preexisting DAST scan
# # Note: It is also important to note that the format for the API Scans JSON is different than that of the Web Application Scans
# # Documentation: 
# #   https://docs.veracode.com/r/c_dynamic_intro
# #   Updating a DAST scan: 
- task: PowerShell@2
  displayName: Veracode DAST Configuration JSON
  inputs:
    targetType: 'inline'
    script: |
      $strB = '{ "name": "Verademo-DA006",  "scans": [ { "scan_config_request": { "target_url": { "url": "http://verademo.bhalpern.vuln.sa.veracode.io/verademo"}, "auth_configuration": { "authentications": { "AUTO": { "username": "$(USERNAME)", "password": "$(PASS)", "authtype": "AUTO"}}}}}],"schedule": {"now": true,"duration": {"length": 1,"unit": "DAY"}}}'        
      Write-Output $strB | Out-file -FilePath ./input.json
      ls
      python --version
      python -m pip install --upgrade pip wheel
      python -m pip install httpie
      git clone https://github.com/veracode/veracode-python-hmac-example.git
      cd veracode-python-hmac-example
      pip install -r requirements.txt
      
      #$str = '{"name": "Verademo-DA006", "schedule": { "duration": { "length": 1, "unit": "DAY" }, "scheduled": true, "now": true } }' 
      #Get-Content input.json |  http --auth-type=veracode_hmac PUT "https://api.veracode.com/was/configservice/v1/analyses/$(ANALYSIS_ID)?method=patch" 

# #########################################################################
# # Downloading and installing HTTPIE for HMAC REST Requests
# #########################################################################
# # HTTPIE documentation: https://httpie.io/docs/cli/universal
# # Veracode Documentation: https://docs.veracode.com/r/c_httpie_tool
