name: .NET

on:
#  push: 
#    branches:
#      - main
  workflow_dispatch:

env:
   DOTNET_VERSION: '4.5.2'
   ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  

jobs:
  build:
    name: build-and-sca
    runs-on: windows-latest
    # grants permissions for the artifact to be uploaded
    permissions:
      contents: read
      packages: write
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can acces it and clones the repo
      - uses: actions/checkout@v3
      # Set up DOT.NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        #with:
        #  dotnet-version: ${{env.DOTNET_VERSION}}
      # Set up MSBuild and add to path  
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        
   
      
      # Set up NuGet to install NuGet dependencies
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
#      - name: Navigate to Workspace
#        run: cd $GITHUB_WORKSPACE

      
      # Restore dependencies to the project
      - name: Install dependencies
        run: dotnet restore
      
      # NuGet call to restore packages
      - name: Restore Packages
        run: nuget restore Verademo-dotnet.sln

# Results in an error not finding the solution files to build off, possibly due to being --no-restore
#      - name: Build
#        run: dotnet build 
#      - name: Test
#        run: dotnet test --no-restore --verbosity normal

         # [DEBUG]: listing directories after MSBUILD
      - name: Veracode Dependency Scanning
        # You may pin to the exact commit or the version.
        # uses: veracode/veracode-sca@d8ce4a08eebf1a6c5e7759c1dc53c1172a3e7e64
        uses: veracode/veracode-sca@v1.09
        with:
          # Authorization token to query and create issues
          github_token: $ {{ secrets.GH_TOKEN }}
          # 
          quick: false # optional, default is false
          # Show update advisor
          update_advisor: true # optional, default is false
          # A git URL to work with in case the scan is not for the current repository
          url: https://github.com/bnreplah/verademo-dotnet # optional, default is 
          # The minimum CVSS value for vulnerability to be added as an issue
          min-cvss-for-issue: 0 # optional, default is 0
          # The maximum allowed cvss in found vulnerabilities to pass the step
          #fail-on-cvss: # optional, default is 10
          # An attribute to instruct the action to create an issue from found vulnerability or just simple text output
          create-issues: true # optional, default is false
          # A path within the repository where the build definition starts
          #path: # optional, default is .
          # Run the SRCCLR in debug mode
          debug: true # optional, default is false
          # Run the SRCCLR with the `--skip-collectors` options
          #skip-collectors: # optional, default is false
          # Run the SRCCLR with the `--allow-dirty` option
          allow-dirty: true # optional, default is false
          # Run the SRCCLR with the `--recursive` option
          recursive: true # optional, default is false

      # Build the solution
      - name: Build Solution
        run: |
          msbuild.exe Verademo-dotnet.sln  /nologo /nr:false /p:DeployOnBuild=true /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:DeleteExistingFiles=false /p:SkipInvalidConfigurations=true /p:PackageLocation=./.. /p:DebugSymbols=true  /p:platform="Any CPU" /p:configuration="Debug" 
      

      - name: List files in the repository and zip artifact
        run: |
          dir ${{ github.workspace }}
   #       Compress-Archive -Path ${{ github.workspace }} -DestinationPath Verademo-dotnet.zip
      - run: ls
      
       # Upload the artifact of the zip archive
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Verademo-dotnet
          path: "Verademo-dotnet.zip" 
          
          
          


